### ISSUE TITLE
Manuell inmatning av ProvID

### ISSUE THREAD

**Issue by mskoldSU** [mskoldSU/lab_templates#1]
Vid diskussion med Nellie på labbet kom vi fram till att det i nuläget blir enklast om ProvID genereras manuellt på liknande sätt som AccNr, dvs genom att mata in ett första värde (t.ex. Q2022/00001). Här kan ProvID Grupp-listan användas för att kopiera ProvID istället för att ha en Copy-from-above knapp.

I resultatmallen skall kolumnen "Sample code of analytical lab" lämnas tom, "NRM's sample code" döpas om till "Accession number", och en ny kolumn "NRM's sample code" skall innehålla ProvID.

**Comment by LogFlames** [comment]
Kan man anta att det första provIDt som matats in är det som resten ska utgå ifrån? 
Om man t.ex. har matat in följande:

| ProvID-från |    | ProvID-till | ProvID-grupp |
|-------------|----|-------------|--------------|
| Q2022/00001 | -> | Q2022/00001 | 1            |
|             | -> |             | 2            |
|             | -> |             | 2            |

Är det då givet att nästa grupp har följande ProvIDn?

| ProvID-från |    | ProvID-till | ProvID-grupp |
|-------------|----|-------------|--------------|
| Q2022/00001 | -> | Q2022/00010 | 1            |
| Q2022/00011 | -> | Q2022/00021 | 2            |
| Q2022/00011 | -> | Q2022/00021 | 2            |

Jag funderar på om man måste hålla koll på vilka ProvIDn som är inmatade och vilka som är automatiskt genererade för att inte skriva över de som är inmatade. Eller ska man behöva mata in en i varje grupp och att den automatiskt kopieras till resten i den gruppen?

**Comment by mskoldSU** [comment]
Så som jag uppfattar det kan man inte lita på att "ProvID-från" följer efter senaste "ProvID-till". "ProvID-till" får nog matas in manuellt utan några kontroller. Jag tänker att man i ovanstående alternativt kan strunta i att använda "ProvID-grupp"-kopiering och istället matat in Q2022/00011 två gånger (så att "ProvID-grupp"-kolumnen blivit 1, 2, 3).

**Comment by LogFlames** [comment]
:+1: 
I vilka situationer kommer då ProvID-gruppen att användas? Eller ska den tas bort?

Edit:
Eller ska ProvID-gruppen inte matas in av användaren, utan updateras utifrån ProvID-från för att man ska kunna kolla att det blivit rätt?

**Comment by mskoldSU** [comment]
Låt oss diskutera dess existens när du är på plats.

**Comment by LogFlames** [comment]
ProvID-gruppen är nu bortkomenterad och man kan mata in ProvID likt AccNR. ProvIDt visas sedan korrekt i export-menyn
