### ISSUE TITLE
Editering av provberedningstabell

### ISSUE THREAD

**Issue by mskoldSU** [mskoldSU/lab_templates#2]
Ibland får man inte ihop tillräckligt med material för någon analys. Då vore det bra att kunna redigera provberedningstabellen (innehållet i provberednings_tabell.csv) inifrån appen, t.ex. minska antalet sillar från 10 till 9 i någon ruta.

**Comment by LogFlames** [comment]
En funktion att kunna expandera en rad i "Set AccNR" menyn och se alla homogenat separat. Sedan kunna ändra storleken på varje homogenat i de expanderade raderna.

**Comment by LogFlames** [comment]
This has been implemented in master
